version: '3'
services:
  tftp:
    restart: always
    container_name: tftp
    build: .
    network_mode: host
    volumes:
      - ./tftpboot:/tftpboot
      - /etc/docsistftp.yaml:/etc/docsistftp.yaml
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "10"
